Package into RPM

diff --git a/src/dsync-sync b/src/dsync-sync
--- a/src/dsync-sync
+++ b/src/dsync-sync
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+set -euxo pipefail
+
+if [ $EUID -ne 0 ]; then
+	echo "ERROR: $0 must be run as root" >&2
+	exit 1
+fi
+
 LOCAL=/home/vraiti/.local
 URL=quay.io/vraiti/dsync
 VAR=/var/lib/dsync
